- name: Demo on Playbook level variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{ URL }}

# Note: variables of one play cannot be accessed other play(by defaul)
